DROP TABLE IF EXISTS users;

CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    first VARCHAR(200) NOT NULL,
    last VARCHAR(200) NOT NULL,
    email VARCHAR(200) NOT NULL UNIQUE,
    bio VARCHAR(200),
    password VARCHAR(100) NOT NULL,
    image_url VARCHAR(300)
);

SELECT * FROM users;
